[build]
publish = "_site"
command = "npm run build-production"

[[redirects]]
from = "/preview/:id/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"
